In [5]:
import pandas as pd
import re

In [28]:
df = pd.read_csv('date_parser_testcases.csv')

In [30]:
df

,Input,Expected Output,Parsed_Date
0,"The event will take place on March 5, 2023.",05/03/2023,05/03/2023
1,Her birthday is on 07/08/1990.,07/08/1990,07/08/1990
2,The deadline is 2022-12-31.,31/12/2022,31/12/2022
3,We met on 1st of January 2000.,01/01/2000,None
4,"The concert is scheduled for 15th September, 2...",15/09/2021,15/09/2021
...,...,...,...
95,"We celebrate Independence Day on 2023-07-04, a...",04/07/2023,04/07/2023
96,The final date for submission is 30th November...,30/11/2022,30/11/2022
97,"The annual conference is on 15th October 2023,...",15/10/2023,15/10/2023
98,"His birthdate, noted as 1990-05-20, is in the ...",20/05/1990,20/05/1990
99,The festival will be celebrated on 12th August...,12/08/2024,12/08/2024

In [45]:
import re

def pd(text):
    # Dictionary to map month names to their respective numbers
    month_mapping = {
        'january': '01', 'february': '02', 'march': '03', 'april': '04',
        'may': '05', 'june': '06', 'july': '07', 'august': '08',
        'september': '09', 'october': '10', 'november': '11', 'december': '12'
    }
    
    # Regular expression to extract day, month, and year
    date_pattern = re.compile(
        r'(\d{1,2})(?:st|nd|rd|th)?\s*(of\s*)?(January|February|March|April|May|June|July|August|September|October|November|December)\s*,?\s*(\d{4})',
        re.IGNORECASE
    )
    
    match = date_pattern.search(text)
    if match:
        day = match.group(1).zfill(2)
        month = month_mapping[match.group(3).lower()]
        year = match.group(4)
        return f"{day}/{month}/{year}"
    return None

# Example usage
text = "We met on 1st of January 2000."
parsed_date = pd(text)
print(parsed_date)  # Output: 01/01/2000

01/01/2000

In [47]:
import re
import pandas as pd

def parse_date(text):
    # Dictionary to map month names and abbreviations to their respective numbers
    month_mapping = {
        'jan': '01', 'january': '01',
        'feb': '02', 'february': '02',
        'mar': '03', 'march': '03',
        'apr': '04', 'april': '04',
        'may': '05',
        'jun': '06', 'june': '06',
        'jul': '07', 'july': '07',
        'aug': '08', 'august': '08',
        'sep': '09', 'sept': '09', 'september': '09',
        'oct': '10', 'october': '10',
        'nov': '11', 'november': '11',
        'dec': '12', 'december': '12'
    }

    # Define patterns for different date formats
    patterns = [
        # Matches Month Day Year format (e.g., January 1, 2023)
        r'([A-Za-z]+)\s+(\d{1,2})(?:st|nd|rd|th)?(?:\s|,)?\s*(\d{4})',
        # Format: DD/MM/YYYY
        r'(\d{2})/(\d{2})/(\d{4})',
        # Format: YYYY-MM-DD
        r'(\d{4})-(\d{2})-(\d{2})',
        # Format: Day Month Year (e.g., 1st January 2023)
        r'(\d{1,2})(?:st|nd|rd|th)?(?:\s|,)?\s*([A-Za-z]+)\s*,?\s*(\d{4})',
        # Format: DD Month YYYY (e.g., 01 January 2023)
        r'(\d{1,2})\s*([A-Za-z]+)\s*(\d{4})',
        # Format: Month DD, YYYY (e.g., Dec 12, 2022)
        r'([A-Za-z]+)\s+(\d{2}),\s*(\d{4})',
        # Format: DD.MM.YYYY (e.g., 02.04.2022)
        r'(\d{2})\.(?:\s*([A-Za-z]+))?\.(?:\s*(\d{4}))',
        # Format: DD-MM-YYYY (e.g., 31-12-2022)
        r'(\d{2})-(\d{2})-(\d{4})'
    ]

    # Try matching patterns
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            groups = match.groups()
            if len(groups) == 3:
                if pattern == patterns[0]:  # Matches Month Day Year format
                    month, day, year = groups
                    month = month_mapping[month.lower()[:3]]
                    return f'{int(day):02d}/{month}/{year}'
                elif pattern == patterns[1]:  # Matches DD/MM/YYYY format
                    day, month, year = groups
                    return f'{day}/{month}/{year}'
                elif pattern == patterns[2]:  # Matches YYYY-MM-DD format
                    year, month, day = groups
                    return f'{day}/{month}/{year}'
                elif pattern == patterns[3]:  # Matches Day Month Year format
                    day, month, year = groups
                    month = month_mapping[month.lower()[:3]]
                    return f'{int(day):02d}/{month}/{year}'
                elif pattern == patterns[4]:  # Matches DD Month YYYY format
                    day, month, year = groups
                    month = month_mapping[month.lower()[:3]]
                    return f'{int(day):02d}/{month}/{year}'
                elif pattern == patterns[5]:  # Matches Month DD, YYYY format
                    month, day, year = groups
                    month = month_mapping[month.lower()[:3]]
                    return f'{int(day):02d}/{month}/{year}'
                elif pattern == patterns[6]:  # Matches DD.MM.YYYY format
                    day, month, year = groups
                    month = month_mapping.get(month.lower(), '01')
                    return f'{day}/{month}/{year}'
                elif pattern == patterns[7]:  # Matches DD-MM-YYYY format
                    day, month, year = groups
                    return f'{day}/{month}/{year}'
    
    # Fallback to pd function if no match is found
    return pd_fallback(text)

def pd_fallback(text):
    # Dictionary to map month names to their respective numbers
    month_mapping = {
        'january': '01', 'february': '02', 'march': '03', 'april': '04',
        'may': '05', 'june': '06', 'july': '07', 'august': '08',
        'september': '09', 'october': '10', 'november': '11', 'december': '12'
    }
    
    # Regular expression to extract day, month, and year
    date_pattern = re.compile(
        r'(\d{1,2})(?:st|nd|rd|th)?\s*(of\s*)?(January|February|March|April|May|June|July|August|September|October|November|December)\s*,?\s*(\d{4})',
        re.IGNORECASE
    )
    
    match = date_pattern.search(text)
    if match:
        day = match.group(1).zfill(2)
        month = month_mapping[match.group(3).lower()]
        year = match.group(4)
        return f"{day}/{month}/{year}"
    return None

# Iterate row-wise and apply the parse_date function
parsed_dates = []
for index, row in df.iterrows():
    parsed_date = parse_date(row['Input'])
    parsed_dates.append(parsed_date)

# Add the parsed dates to the dataframe
df['Parsed_Date'] = parsed_dates

# Check for missing values in the Parsed_Date column
missing_values = df['Parsed_Date'].isna().sum()

# Display the dataframe and the count of missing parsed dates
df

,Input,Expected Output,Parsed_Date
0,"The event will take place on March 5, 2023.",05/03/2023,05/03/2023
1,Her birthday is on 07/08/1990.,07/08/1990,07/08/1990
2,The deadline is 2022-12-31.,31/12/2022,31/12/2022
3,We met on 1st of January 2000.,01/01/2000,01/01/2000
4,"The concert is scheduled for 15th September, 2...",15/09/2021,15/09/2021
...,...,...,...
95,"We celebrate Independence Day on 2023-07-04, a...",04/07/2023,04/07/2023
96,The final date for submission is 30th November...,30/11/2022,30/11/2022
97,"The annual conference is on 15th October 2023,...",15/10/2023,15/10/2023
98,"His birthdate, noted as 1990-05-20, is in the ...",20/05/1990,20/05/1990
99,The festival will be celebrated on 12th August...,12/08/2024,12/08/2024